# Generated by Django 2.1 on 2019-06-01 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('doc_identificacao', models.CharField(max_length=12)),
                ('doc_tipo', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=15)),
                ('cep', models.CharField(max_length=9, blank=False, null=False)),
                ('curso', models.CharField(max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
