# Generated by Django 2.1 on 2019-06-01 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=18)),
                ('tipo_processo', models.TextField()),
                ('esclarecimentos', models.TextField()),
                ('natureza_processo', models.CharField(max_length=100)),
                ('parecer', models.CharField(max_length=40)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.UserData')),
            ],
        ),
    ]
